apiVersion: v1
name: minecraft
description: Helm chart used to deploy the Minecraft for Kubernetes
home: https://minecraft.net/
icon: https://cdn2.steamgriddb.com/icon_thumb/0a17ad0fa0870b05f172deeb05efef8e.png

type: application

version: 0.2.0
appVersion: v5.0.0

sources:
    - https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft
    - https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be