apiVersion: v1
name: minecraft
description: Helm chart used to deploy the Minecraft for Kubernetes
home: https://minecraft.net/
icon: https://1000logos.net/wp-content/uploads/2018/10/Minecraft-Logo-2013.png

type: application

version: 0.1.0
appVersion: v5.0.0

sources:
    - https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft
    - https://artifacthub.io/packages/helm/minecraft-server-charts/minecraft

maintainers:
    - name: James Flanders
      email: jens.caenen@telenet.be