###############################################################
# Common
###############################################################

# Name of the application
app: "slagerij-rob"

###############################################################
# Accessibility
###############################################################

# Name of the DNS record to link to the container.
host: "slagerij-rob.caenen.net"

# Credentials for PostgreSQL Database
database_username: "f1100679-d0be-40c6-ba85-0a02000eedec"
database_password: "vHubMfOYpsZ447YU8qF4hjQ42W708k"
database_hostname: "slagerij-rob-database-service"
database_port: "5432"

# Include the creation of the database secret
include_database_secret: false

###############################################################
# Volumes and Storage
###############################################################

# Include the creation of the PersistentVolumeClaim
include_volumes: false

##### The following parameters only apply if 'include_volumes' is set to 'true' #####

# Name of the 'StorageClass' to use for the PersistentVolumeClaim.
storage_class_name: "nfs"

# Size of the PersistentVolumeClaim.
storage_size: "500Mi"