apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-backend
    spec:
      containers:
      - name: {{ .Values.app }}-backend
        image: ghcr.io/jamesflanders/{{.Values.app}}-backend:0.1.1
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: {{ .Values.app }}-database-secret
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: {{ .Values.app }}-database-secret
          - name: DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: hostname
                name: {{ .Values.app }}-database-secret
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                key: port
                name: {{ .Values.app }}-database-secret
      imagePullSecrets:
        - name: github-container-registry-secret