apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app }}-backend-certificate
spec:
  secretName: {{ .Values.app }}-backend-caenen-net-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: caenen.net
  dnsNames:
  - caenen.net
  - "slagerij-rob-backend.caenen.net"