apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.app }}-database-stateful-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-database
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-database
    spec:
      containers:
        - name: {{ .Values.app }}-database
          image: postgres:17.6-alpine
          ports:
            - containerPort: 5432
              name: database
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.app }}-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.app }}-database-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.app }}-database-secret
      volumes:
        - name: {{ .Values.app }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-data-pvc
