{{ if .Values.include_database_secret }}
apiVersion: v1
data:
  hostname: {{ .Values.database_hostname }}
  password: {{ .Values.database_password }}
  port: {{ .Values.database_port }}
  username: {{ .Values.database_username }}
kind: Secret
metadata:
  name: {{ .Values.app }}-database-secret
type: Opaque
{{ end }}