{{ if .Values.include_database_secret }}
apiVersion: v1
stringData:
  hostname: {{ .Values.database_hostname | quote }}
  password: {{ .Values.database_password | quote }}
  port: {{ .Values.database_port | quote }}
  username: {{ .Values.database_username | quote }}
kind: Secret
metadata:
  name: {{ .Values.app }}-database-secret
type: Opaque
{{ end }}