apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.app }}-frontend
    spec:
      containers:
      - name: {{ .Values.app }}-frontend
        image: ghcr.io/jamesflanders/{{.Values.app}}-frontend:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
        - name: github-container-registry-secret