apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app }}-frontend-certificate
spec:
  secretName: {{ .Values.app }}-frontend-caenen-net-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: caenen.net
  dnsNames:
  - caenen.net
  - "{{ .Values.host }}"