{{ if .Values.minecraft_bluemap_enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-bluemap-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8100
  selector:
    app: {{ .Values.app }}
{{end}}