{{ if .Values.minecraft_bluemap_enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.app }}-bluemap-certificate
spec:
  secretName: {{ .Values.app }}-bluemap-caenen-net-tls
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  commonName: caenen.net
  dnsNames:
  - caenen.net
  - "{{ .Values.minecraft_bluemap_host }}"
{{end}}