apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-server-service
spec:
  type: NodePort
  ports:
  - name: tcp
    protocol: TCP
    port: 25565
    targetPort: {{ .Values.port }}
  - name: udp
    protocol: UDP
    port: 25565
    targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.app }}