apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app }}-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}
          image: "itzg/minecraft-server:{{.Values.image_tag}}"
          ports:
            - containerPort: 25565
              name: tcp
              protocol: TCP
            - containerPort: 25565
              name: udp
              protocol: UDP
          env:
            - name: EULA
              value: {{ .Values.minecraft_eula | quote }}
            - name: VERSION
              value: {{ .Values.minecraft_version | quote }}
            - name: TYPE
              value: {{ .Values.minecraft_type | quote }}
            - name: INIT_MEMORY
              value: {{ .Values.minecraft_init_memory | quote }}
            - name: MAX_MEMORY
              value: {{ .Values.minecraft_max_memory | quote }}
            - name: MAX_PLAYERS
              value: {{ .Values.minecraft_max_players | quote }}
            - name: PVP
              value: {{ .Values.minecraft_pvp | quote }}
            {{ if .Values.minecraft_seed }}
            - name: SEED
              value: {{ .Values.minecraft_seed | quote }}
            {{end}}
            - name: TZ
              value: {{ .Values.minecraft_timezone | quote }}
          volumeMounts:
            - name: {{ .Values.app }}-data
              mountPath: /data
      volumes:
        - name: {{ .Values.app }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.app }}-data-pvc